/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthenticatedRubricsIndexRouteImport } from './routes/_authenticated/rubrics/index'
import { Route as AuthenticatedRubricsNewRouteImport } from './routes/_authenticated/rubrics/new'
import { Route as AuthenticatedSubmissionsIndexRouteImport } from './routes/_authenticated/submissions/index'
import { Route as AuthenticatedSubmissionsNewRouteImport } from './routes/_authenticated/submissions/new'
import { Route as AuthenticatedRubricsRubricIdIndexRouteImport } from './routes/_authenticated/rubrics/$rubricId/index'
import { Route as AuthenticatedRubricsRubricIdEditRouteImport } from './routes/_authenticated/rubrics/$rubricId/edit'
import { Route as AuthenticatedSubmissionsSubmissionIdIndexRouteImport } from './routes/_authenticated/submissions/$submissionId/index'
import { Route as AuthenticatedSubmissionsSubmissionIdEditRouteImport } from './routes/_authenticated/submissions/$submissionId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRubricsIndexRoute =
  AuthenticatedRubricsIndexRouteImport.update({
    id: '/rubrics/',
    path: '/rubrics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRubricsNewRoute = AuthenticatedRubricsNewRouteImport.update({
  id: '/rubrics/new',
  path: '/rubrics/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubmissionsIndexRoute =
  AuthenticatedSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubmissionsNewRoute =
  AuthenticatedSubmissionsNewRouteImport.update({
    id: '/submissions/new',
    path: '/submissions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRubricsRubricIdIndexRoute =
  AuthenticatedRubricsRubricIdIndexRouteImport.update({
    id: '/rubrics/$rubricId/',
    path: '/rubrics/$rubricId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRubricsRubricIdEditRoute =
  AuthenticatedRubricsRubricIdEditRouteImport.update({
    id: '/rubrics/$rubricId/edit',
    path: '/rubrics/$rubricId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubmissionsSubmissionIdIndexRoute =
  AuthenticatedSubmissionsSubmissionIdIndexRouteImport.update({
    id: '/submissions/$submissionId/',
    path: '/submissions/$submissionId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubmissionsSubmissionIdEditRoute =
  AuthenticatedSubmissionsSubmissionIdEditRouteImport.update({
    id: '/submissions/$submissionId/edit',
    path: '/submissions/$submissionId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/rubrics/new': typeof AuthenticatedRubricsNewRoute
  '/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/rubrics/': typeof AuthenticatedRubricsIndexRoute
  '/submissions/': typeof AuthenticatedSubmissionsIndexRoute
  '/rubrics/$rubricId/edit': typeof AuthenticatedRubricsRubricIdEditRoute
  '/submissions/$submissionId/edit': typeof AuthenticatedSubmissionsSubmissionIdEditRoute
  '/rubrics/$rubricId/': typeof AuthenticatedRubricsRubricIdIndexRoute
  '/submissions/$submissionId/': typeof AuthenticatedSubmissionsSubmissionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/rubrics/new': typeof AuthenticatedRubricsNewRoute
  '/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/rubrics': typeof AuthenticatedRubricsIndexRoute
  '/submissions': typeof AuthenticatedSubmissionsIndexRoute
  '/rubrics/$rubricId/edit': typeof AuthenticatedRubricsRubricIdEditRoute
  '/submissions/$submissionId/edit': typeof AuthenticatedSubmissionsSubmissionIdEditRoute
  '/rubrics/$rubricId': typeof AuthenticatedRubricsRubricIdIndexRoute
  '/submissions/$submissionId': typeof AuthenticatedSubmissionsSubmissionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/rubrics/new': typeof AuthenticatedRubricsNewRoute
  '/_authenticated/submissions/new': typeof AuthenticatedSubmissionsNewRoute
  '/_authenticated/rubrics/': typeof AuthenticatedRubricsIndexRoute
  '/_authenticated/submissions/': typeof AuthenticatedSubmissionsIndexRoute
  '/_authenticated/rubrics/$rubricId/edit': typeof AuthenticatedRubricsRubricIdEditRoute
  '/_authenticated/submissions/$submissionId/edit': typeof AuthenticatedSubmissionsSubmissionIdEditRoute
  '/_authenticated/rubrics/$rubricId/': typeof AuthenticatedRubricsRubricIdIndexRoute
  '/_authenticated/submissions/$submissionId/': typeof AuthenticatedSubmissionsSubmissionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/rubrics/new'
    | '/submissions/new'
    | '/rubrics/'
    | '/submissions/'
    | '/rubrics/$rubricId/edit'
    | '/submissions/$submissionId/edit'
    | '/rubrics/$rubricId/'
    | '/submissions/$submissionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/rubrics/new'
    | '/submissions/new'
    | '/rubrics'
    | '/submissions'
    | '/rubrics/$rubricId/edit'
    | '/submissions/$submissionId/edit'
    | '/rubrics/$rubricId'
    | '/submissions/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/rubrics/new'
    | '/_authenticated/submissions/new'
    | '/_authenticated/rubrics/'
    | '/_authenticated/submissions/'
    | '/_authenticated/rubrics/$rubricId/edit'
    | '/_authenticated/submissions/$submissionId/edit'
    | '/_authenticated/rubrics/$rubricId/'
    | '/_authenticated/submissions/$submissionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rubrics/': {
      id: '/_authenticated/rubrics/'
      path: '/rubrics'
      fullPath: '/rubrics/'
      preLoaderRoute: typeof AuthenticatedRubricsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rubrics/new': {
      id: '/_authenticated/rubrics/new'
      path: '/rubrics/new'
      fullPath: '/rubrics/new'
      preLoaderRoute: typeof AuthenticatedRubricsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/submissions/': {
      id: '/_authenticated/submissions/'
      path: '/submissions'
      fullPath: '/submissions/'
      preLoaderRoute: typeof AuthenticatedSubmissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/submissions/new': {
      id: '/_authenticated/submissions/new'
      path: '/submissions/new'
      fullPath: '/submissions/new'
      preLoaderRoute: typeof AuthenticatedSubmissionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rubrics/$rubricId/': {
      id: '/_authenticated/rubrics/$rubricId/'
      path: '/rubrics/$rubricId'
      fullPath: '/rubrics/$rubricId/'
      preLoaderRoute: typeof AuthenticatedRubricsRubricIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rubrics/$rubricId/edit': {
      id: '/_authenticated/rubrics/$rubricId/edit'
      path: '/rubrics/$rubricId/edit'
      fullPath: '/rubrics/$rubricId/edit'
      preLoaderRoute: typeof AuthenticatedRubricsRubricIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/submissions/$submissionId/': {
      id: '/_authenticated/submissions/$submissionId/'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId/'
      preLoaderRoute: typeof AuthenticatedSubmissionsSubmissionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/submissions/$submissionId/edit': {
      id: '/_authenticated/submissions/$submissionId/edit'
      path: '/submissions/$submissionId/edit'
      fullPath: '/submissions/$submissionId/edit'
      preLoaderRoute: typeof AuthenticatedSubmissionsSubmissionIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedRubricsNewRoute: typeof AuthenticatedRubricsNewRoute
  AuthenticatedSubmissionsNewRoute: typeof AuthenticatedSubmissionsNewRoute
  AuthenticatedRubricsIndexRoute: typeof AuthenticatedRubricsIndexRoute
  AuthenticatedSubmissionsIndexRoute: typeof AuthenticatedSubmissionsIndexRoute
  AuthenticatedRubricsRubricIdEditRoute: typeof AuthenticatedRubricsRubricIdEditRoute
  AuthenticatedSubmissionsSubmissionIdEditRoute: typeof AuthenticatedSubmissionsSubmissionIdEditRoute
  AuthenticatedRubricsRubricIdIndexRoute: typeof AuthenticatedRubricsRubricIdIndexRoute
  AuthenticatedSubmissionsSubmissionIdIndexRoute: typeof AuthenticatedSubmissionsSubmissionIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRubricsNewRoute: AuthenticatedRubricsNewRoute,
  AuthenticatedSubmissionsNewRoute: AuthenticatedSubmissionsNewRoute,
  AuthenticatedRubricsIndexRoute: AuthenticatedRubricsIndexRoute,
  AuthenticatedSubmissionsIndexRoute: AuthenticatedSubmissionsIndexRoute,
  AuthenticatedRubricsRubricIdEditRoute: AuthenticatedRubricsRubricIdEditRoute,
  AuthenticatedSubmissionsSubmissionIdEditRoute:
    AuthenticatedSubmissionsSubmissionIdEditRoute,
  AuthenticatedRubricsRubricIdIndexRoute:
    AuthenticatedRubricsRubricIdIndexRoute,
  AuthenticatedSubmissionsSubmissionIdIndexRoute:
    AuthenticatedSubmissionsSubmissionIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
